version: "3.7"

services:
  r-proxy:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./index.html:/var/www/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  rmq:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15671-15672:15671-15672"
      - "5672:5672"
