version: "3.7"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=backend
    logging:
      driver: none

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./default_conf.conf:/etc/nginx/conf.d/default.conf
      - ./cache:/data/nginx/cache

